import type { Prisma } from "@prisma/client";
import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

const customers: Prisma.CustomerCreateArgs["data"][] = [
  { name: "BSM" },
  { name: "RR Meatshop" },
  { name: "Jessie" },
  { name: "Harry" },
  { name: "Pablo" },
  { name: "Jumar" },
  { name: "Rufo" },
  { name: "Cabasan" },
  { name: "Dodong Coling" },
  { name: "Dionsay, Frank" },
  { name: "Nanay" },
  { name: "Flores Bonbon (Jessa)" },
  { name: "Estoconing" },
  { name: "Bahian" },
  { name: "Junjie" },
  { name: "BBC" },
  { name: "Dablio" },
  { name: "Baculio" },
  { name: "Amy Urban" },
  { name: "Hazel Urban" },
  { name: "Guligado" },
  { name: "Balingasag" },
  { name: "Bacarro" },
  { name: "Poldo's Lechon" },
  { name: "Agusan" },
];

const suppliers: Prisma.SupplierCreateArgs["data"][] = [
  { name: "Bersheba" },
  { name: "Cabual Farm" },
  { name: "Cabahug Farm" },
  { name: "Ocapan Farm" },
  { name: "Galeon Farm" },
  { name: "JMRBS Livestock Farm/Saguin" },
  { name: "So Eng Grace Farm" },
];

const deliveries: Prisma.DeliveryCreateArgs["data"][] = [
  {
    arrivalDate: new Date("2023/2/11"),
    modeOfPayment: "Cash (by Von)",
    supplier: {
      connectOrCreate: {
        where: {
          name: "Cabahug Farm",
        },
        create: {
          name: "Cabahug Farm",
        },
      },
    },
    hogs: {
      createMany: {
        data: [
          {
            farmgatePrice: 195.0,
            eartag: "337",
            liveWeight: 101.5,
            sellingWeight: 105,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "338",
            liveWeight: 111.5,
            sellingWeight: 116,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "339",
            liveWeight: 103.5,
            sellingWeight: 109,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "340",
            liveWeight: 116,
            sellingWeight: 121,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "341",
            liveWeight: 106,
            sellingWeight: 110,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "342",
            liveWeight: 105.5,
            sellingWeight: 106,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "343",
            liveWeight: 106.5,
            sellingWeight: 111,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "344",
            liveWeight: 103,
            sellingWeight: 107,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "345",
            liveWeight: 94.5,
            sellingWeight: 98,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "346",
            liveWeight: 98.5,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "347",
            liveWeight: 97.5,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "348",
            liveWeight: 104.5,
            sellingWeight: 109,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "349",
            liveWeight: 102.5,
            sellingWeight: 106,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "350",
            liveWeight: 96.5,
            sellingWeight: 101,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "351",
            liveWeight: 100.5,
            sellingWeight: 105,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "352",
            liveWeight: 114,
            sellingWeight: 119,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "353",
            liveWeight: 99,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "354",
            liveWeight: 107,
            sellingWeight: 112,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "355",
            liveWeight: 98.5,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "356",
            liveWeight: 102,
            sellingWeight: 106,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "357",
            liveWeight: 105,
            sellingWeight: 108,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "358",
            liveWeight: 108,
            sellingWeight: 112,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "359",
            liveWeight: 95,
            sellingWeight: 108,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "360",
            liveWeight: 102.5,
            sellingWeight: 106,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "361",
            liveWeight: 97.5,
            sellingWeight: 98,
            sellingPrice: 195.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "362",
            liveWeight: 95.5,
            sellingWeight: 99,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "363",
            liveWeight: 101,
            sellingWeight: 105,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "364",
            liveWeight: 101,
            sellingWeight: 101,
            sellingPrice: 195.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "365",
            liveWeight: 95.5,
            sellingWeight: 99,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "366",
            liveWeight: 103.5,
            sellingWeight: 99,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "367",
            liveWeight: 98,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "368",
            liveWeight: 104.5,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "369",
            liveWeight: 107,
            sellingWeight: 107,
            sellingPrice: 0.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "370",
            liveWeight: 97.5,
            sellingWeight: 101,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "371",
            liveWeight: 99,
            sellingWeight: 108,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "372",
            liveWeight: 100,
            sellingWeight: 104,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "373",
            liveWeight: 99.5,
            sellingWeight: 100,
            sellingPrice: 195.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "374",
            liveWeight: 101.5,
            sellingWeight: 105,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "375",
            liveWeight: 106,
            sellingWeight: 110,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "376",
            liveWeight: 98.5,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "377",
            liveWeight: 103,
            sellingWeight: 107,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "378",
            liveWeight: 98,
            sellingWeight: 102,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "379",
            liveWeight: 108,
            sellingWeight: 112,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "380",
            liveWeight: 101,
            sellingWeight: 104,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "381",
            liveWeight: 98.5,
            sellingWeight: 101,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "382",
            liveWeight: 104,
            sellingWeight: 107,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "383",
            liveWeight: 99,
            sellingWeight: 103,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "384",
            liveWeight: 91,
            sellingWeight: 94,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "385",
            liveWeight: 93.5,
            sellingWeight: 94,
            sellingPrice: 195.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "386",
            liveWeight: 94.5,
            sellingWeight: 98,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "387",
            liveWeight: 112.5,
            sellingWeight: 113,
            sellingPrice: 0.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "388",
            liveWeight: 108,
            sellingWeight: 112,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "389",
            liveWeight: 97,
            sellingWeight: 100,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "390",
            liveWeight: 101,
            sellingWeight: 104,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "391",
            liveWeight: 100,
            sellingWeight: 103,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "392",
            liveWeight: 106,
            sellingWeight: 106,
            sellingPrice: 195.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "393",
            liveWeight: 93,
            sellingWeight: 96,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "394",
            liveWeight: 110,
            sellingWeight: 114,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "395",
            liveWeight: 108.5,
            sellingWeight: 112,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "396",
            liveWeight: 105,
            sellingWeight: 109,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "397",
            liveWeight: 96.5,
            sellingWeight: 100,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "398",
            liveWeight: 97,
            sellingWeight: 97,
            sellingPrice: 195.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "399",
            liveWeight: 98.5,
            sellingWeight: 101,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "400",
            liveWeight: 93.5,
            sellingWeight: 97,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "085",
            liveWeight: 106,
            sellingWeight: 110,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "086",
            liveWeight: 95.5,
            sellingWeight: 96,
            sellingPrice: 195.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "087",
            liveWeight: 96.5,
            sellingWeight: 100,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "088",
            liveWeight: 106.5,
            sellingWeight: 110,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "099",
            liveWeight: 101,
            sellingWeight: 104,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 195.0,
            eartag: "100",
            liveWeight: 100.5,
            sellingWeight: 101,
            sellingPrice: 0.0,
          },
        ],
      },
    },
  },
  {
    arrivalDate: new Date("2023/2/15"),
    modeOfPayment: "",
    supplier: {
      connectOrCreate: {
        where: {
          name: "Bersheba",
        },
        create: {
          name: "Bersheba",
        },
      },
    },
    hogs: {
      createMany: {
        data: [
          {
            farmgatePrice: 190.0,
            eartag: "1",
            liveWeight: 90.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "2",
            liveWeight: 95.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "3",
            liveWeight: 98.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "5",
            liveWeight: 92.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "6",
            liveWeight: 98.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "8",
            liveWeight: 98.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "9",
            liveWeight: 108.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "10",
            liveWeight: 90.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "11",
            liveWeight: 103.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "21",
            liveWeight: 113.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "22",
            liveWeight: 93.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "31",
            liveWeight: 86.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "32",
            liveWeight: 89.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "33",
            liveWeight: 98.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "34",
            liveWeight: 89.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "35",
            liveWeight: 88.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "37",
            liveWeight: 98.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "38",
            liveWeight: 85.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "40",
            liveWeight: 93.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "41",
            liveWeight: 89.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "42",
            liveWeight: 89.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "44",
            liveWeight: 89.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "47",
            liveWeight: 92.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "49",
            liveWeight: 88.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "50",
            liveWeight: 95.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "51",
            liveWeight: 90.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "52",
            liveWeight: 93.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "55",
            liveWeight: 90.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "56",
            liveWeight: 94.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "57",
            liveWeight: 89.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "58",
            liveWeight: 92.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "59",
            liveWeight: 88.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "63",
            liveWeight: 95.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "64",
            liveWeight: 93.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "66",
            liveWeight: 87.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "67",
            liveWeight: 87.5,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "68",
            liveWeight: 91.0,
            sellingPrice: 0,
            sellingWeight: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "4",
            liveWeight: 97.5,
            sellingPrice: 100.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "7",
            liveWeight: 104.0,
            sellingPrice: 104.0,
            sellingWeight: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "12",
            liveWeight: 97.5,
            sellingPrice: 100.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "13",
            liveWeight: 97.0,
            sellingPrice: 97.0,
            sellingWeight: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "14",
            liveWeight: 94.0,
            sellingPrice: 97.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "15",
            liveWeight: 96.5,
            sellingPrice: 100.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "16",
            liveWeight: 97.5,
            sellingPrice: 100.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "17",
            liveWeight: 99.5,
            sellingPrice: 102.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "18",
            liveWeight: 92.0,
            sellingPrice: 95.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "19",
            liveWeight: 87.0,
            sellingPrice: 90.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "20",
            liveWeight: 94.0,
            sellingPrice: 97.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "23",
            liveWeight: 91.0,
            sellingPrice: 94.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "24",
            liveWeight: 100.0,
            sellingPrice: 103.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "25",
            liveWeight: 97.5,
            sellingPrice: 100.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "26",
            liveWeight: 103.0,
            sellingPrice: 106.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "27",
            liveWeight: 89.0,
            sellingPrice: 89.0,
            sellingWeight: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "28",
            liveWeight: 87.5,
            sellingPrice: 90.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "29",
            liveWeight: 93.0,
            sellingPrice: 96.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "30",
            liveWeight: 84.5,
            sellingPrice: 86.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "36",
            liveWeight: 84.5,
            sellingPrice: 84.5,
            sellingWeight: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "39",
            liveWeight: 84.0,
            sellingPrice: 84.0,
            sellingWeight: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "43",
            liveWeight: 92.0,
            sellingPrice: 94.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "45",
            liveWeight: 84.5,
            sellingPrice: 84.5,
            sellingWeight: 157.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "46",
            liveWeight: 99.0,
            sellingPrice: 102.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "48",
            liveWeight: 84.5,
            sellingPrice: 84.5,
            sellingWeight: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "53",
            liveWeight: 88.0,
            sellingPrice: 88.0,
            sellingWeight: 157.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "54",
            liveWeight: 91.5,
            sellingPrice: 95.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "60",
            liveWeight: 89.0,
            sellingPrice: 92.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "61",
            liveWeight: 88.0,
            sellingPrice: 88.0,
            sellingWeight: 157.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "62",
            liveWeight: 90.5,
            sellingPrice: 93.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "65",
            liveWeight: 92.0,
            sellingPrice: 95.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "69",
            liveWeight: 93.5,
            sellingPrice: 96.0,
            sellingWeight: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "70",
            liveWeight: 97.0,
            sellingPrice: 100.0,
            sellingWeight: 210.0,
          },
        ],
      },
    },
  },
  {
    arrivalDate: new Date("2023/2/9"),
    modeOfPayment: "",
    supplier: {
      connectOrCreate: {
        where: {
          name: "Bersheba",
        },
        create: {
          name: "Bersheba",
        },
      },
    },
    hogs: {
      createMany: {
        data: [
          {
            farmgatePrice: 190.0,
            eartag: "278",
            liveWeight: 97.0,
            sellingWeight: 99.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "277",
            liveWeight: 87.5,
            sellingWeight: 90.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "295",
            liveWeight: 86.5,
            sellingWeight: 89.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "274",
            liveWeight: 93.0,
            sellingWeight: 96.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "273",
            liveWeight: 101.0,
            sellingWeight: 104.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "296",
            liveWeight: 93.0,
            sellingWeight: 96.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "288",
            liveWeight: 94.5,
            sellingWeight: 97.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "327",
            liveWeight: 102.5,
            sellingWeight: 106.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "334",
            liveWeight: 103.5,
            sellingWeight: 107.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "321",
            liveWeight: 102.5,
            sellingWeight: 105.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "331",
            liveWeight: 103.5,
            sellingWeight: 107.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "326",
            liveWeight: 108.5,
            sellingWeight: 112.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "332",
            liveWeight: 105.5,
            sellingWeight: 109.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "284",
            liveWeight: 98.0,
            sellingWeight: 101.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "291",
            liveWeight: 86.0,
            sellingWeight: 89.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "292",
            liveWeight: 86.0,
            sellingWeight: 86.0,
            sellingPrice: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "280",
            liveWeight: 100.0,
            sellingWeight: 100.0,
            sellingPrice: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "288",
            liveWeight: 94.5,
            sellingWeight: 98.0,
            sellingPrice: 210.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "267",
            liveWeight: 95.0,
            sellingWeight: 95.0,
            sellingPrice: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "?",
            liveWeight: 0,
            sellingWeight: 0,
            sellingPrice: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "?",
            liveWeight: 0,
            sellingWeight: 0,
            sellingPrice: 0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "305",
            liveWeight: 91.0,
            sellingWeight: 91.0,
            sellingPrice: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "307",
            liveWeight: 86.5,
            sellingWeight: 86.5,
            sellingPrice: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "299",
            liveWeight: 95.0,
            sellingWeight: 95.0,
            sellingPrice: 190.0,
          },
          {
            farmgatePrice: 190.0,
            eartag: "276",
            liveWeight: 91.5,
            sellingWeight: 95.0,
            sellingPrice: 210.0,
          },
        ],
      },
    },
  },
];

async function seed() {
  await Promise.all(
    suppliers.map((data) => {
      return db.supplier.create({ data });
    })
  );
  await Promise.all(
    deliveries.map((data) => {
      return db.delivery.create({ data });
    })
  );
  await Promise.all(
    customers.map((data) => {
      return db.customer.create({ data });
    })
  );
}

seed();
